language: python
python:
  - "2.7"
services:
  - memcached
env:
  global:
    - DJANGO_SETTINGS_MODULE=esp.settings
  matrix:
    - TRAVIS_JOB="lint"
    - TRAVIS_JOB="test"
before_install:
  - deploy/travis/before_install
install:
  - deploy/travis/install
before_script:
  - deploy/travis/before_script
script:
  - deploy/travis/script
