language: python
python:
  - "2.7"
services:
  - postgresql
  - memcached
env: DJANGO_SETTINGS_MODULE=esp.settings
before_install:
  - sudo apt-get update
install: 
  - sudo apt-get install -y $(< esp/packages_base.txt)
  # Fiddle with packages to get node and LESS set up
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/libv/libv8/libv8-3.8.9.20_3.8.9.20-2_amd64.deb -O libv8.deb
  - sudo dpkg -i libv8.deb
  - sudo apt-get install libc-ares2 libev4
  - sudo bash esp/packages_base_manual_install.sh
  - pip install -r esp/requirements.txt --use-mirrors
before_script:
  - cp esp/esp/local_settings.py.travis esp/esp/local_settings.py
  - ln -s `pwd`/esp/public/media/default_images esp/public/media/images
  - ln -s `pwd`/esp/public/media/default_styles esp/public/media/styles
  - psql -c "CREATE ROLE testuser PASSWORD 'testpassword' LOGIN CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE test_django OWNER testuser;" -U postgres
script: 
  - cd esp
  - ./manage.py test
notifications:
  email: false  # disable emails until we configure the tests
