language: python
python:
  - "2.7"
services:
  - postgresql
  - memcached
env: DJANGO_SETTINGS_MODULE=esp.settings
before_install:
  - sudo apt-get update
install: 
  - sudo apt-get install -y $(< esp/packages.txt)
  - pip install -r esp/requirements.txt --use-mirrors
before_script:
  - cp esp/esp/local_settings.py.travis esp/esp/local_settings.py
  - cd esp/public/media && ln -s default_images images
  - cd esp/public/media && ln -s default_styles styles
  - psql -c "CREATE ROLE testuser PASSWORD 'testpassword' LOGIN CREATEDB;" -U postgres
  - psql -c "CREATE DATABASE test_django OWNER testuser;" -U postgres
script: 
  - cd esp
  - ./manage.py test
